###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################
based_on_package: "cybertech_mock"

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  # Set simulated to false if you are using this as a configuration for real hardware.
  # This allows users to switch between mock and real hardware by changing a single parameter with config inheritance.
  # [Required]
  simulated: false

  # If the MoveIt Pro Agent should launch the ros2 controller node.
  # [Optional, default=True]
  launch_control_node: False

  # If simulated is false, launch the following file:
  # [Optional, defaults to a blank launch file if not specified]
  robot_driver_persist_launch_file:
    package: "cybertech_hw"
    path: "launch/robot_drivers_to_persist.launch.py"

  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
      - mode: "hardware"
      - driver_version: "rsi_only"
      - use_gpio: "false"
      - client_ip: "0.0.0.0"
      - client_port: "59152"
      - controller_ip: "127.0.0.1"

# Sets ROS global params for launch.
# [Optional]
ros_global_params:
  # Whether or not to use simulated time.
  # [Optional, default=False]
  use_sim_time: False

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  config:
    package: "cybertech_hw"
    path: "config/control/ros2_control.yaml"
  # MoveIt Pro will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup: []
  # Load but do not start these controllers so they can be activated later if needed.
  # [Optional, default=[]]
  controllers_inactive_at_startup:
    - "joint_state_broadcaster"
    - "joint_trajectory_controller"
  # Any controllers here will not be spawned by MoveIt Pro.
  # [Optional, default=[]]
  controllers_not_managed:
    - "velocity_force_controller"
    - "servo_controller"
# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  objective_library_paths:
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    mock_objectives:
      package_name: "cybertech_mock"
      relative_path: "objectives"
    hw_objectives:
      package_name: "cybertech_hw"
      relative_path: "objectives"
