# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_a1:
    has_velocity_limits: true
    max_velocity: 1.832596
    has_acceleration_limits: true
    max_acceleration: 3.0
    max_deceleration: 3.0
  joint_a2:
    has_velocity_limits: true
    max_velocity: 1.640609
    has_acceleration_limits: true
    max_acceleration: 5.0
    max_deceleration: 5.0
  joint_a3:
    has_velocity_limits: true
    max_velocity: 1.745329
    has_acceleration_limits: true
    max_acceleration: 5.0
    max_deceleration: 5.0
  joint_a4:
    has_velocity_limits: true
    max_velocity: 2.373648
    has_acceleration_limits: true
    max_acceleration: 3.0
    max_deceleration: 3.0
  joint_a5:
    has_velocity_limits: true
    max_velocity: 2.251475
    has_acceleration_limits: true
    max_acceleration: 5.0
    max_deceleration: 5.0
  joint_a6:
    has_velocity_limits: true
    max_velocity: 3.595378
    has_acceleration_limits: true
    max_acceleration: 7.0
    max_deceleration: 7.0
